version: '3.7'

services:
  anyway:
    build: .
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=postgresql://anyway:anyway@db/anyway
    volumes:
      - .:/anyway
    restart: always
    depends_on:
      - db

  db:
    build: db_docker 
    environment:
      - POSTGRES_PASSWORD=anyway
      - POSTGRES_USER=anyway
      - POSTGRES_DB=anyway
    volumes:
      - db_data:/var/lib/postgresql/data  
    restart: always

volumes: 
  db_data:
